---
- name: Indy-Pool Server Host Build
  hosts: all
  gather_facts: true

  vars:
    pip_install_packages:
      - name: docker
  
  roles:
    - role: lumberjack-build
    - role: geerlingguy.docker
      become: true
  
  tasks:

  - name: Start Docker Service
    service: 
      name: docker
      state: started
  
  - name: Launch Indy-SDK Juypter notebook with docker-compose up
    command: docker-compose build -d
    args:
      chdir: ~/indy-sdk/docs/getting-started